config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: 'visitors#index'
  devise_for :users
  resources :users do
    resources :routes do
      resources :alerts
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :routes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.slim
.container
  .row
    h3 Users
    .column
      table.table
        tbody
          - @users.each do |user|
            tr
              = render user

app/views/users/show.html.slim
h3
  = @user.name
  - if current_user.id == @user.id
    = link_to '', edit_user_registration_path(@user), class: 'btn btn-sm glyphicon glyphicon-pencil', style: 'margin-left: 10px;'

.details
  | Email: &nbsp;
  = @user.email

br

h4 My Routes

ul.list-group

- @user.routes.each do |route|
  li.list-group-item style="max-width: 400px;"
    = link_to route.name, user_route_path(@user, route)

    = link_to '✕', [current_user, @route], data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-xs btn-danger', style: 'float: right; color: white; margin-left: 10px;'

    span.badge.badge-primary
      = pluralize(route.alerts.count, 'alert')

= link_to 'New Route...', new_user_route_path(@user), class: 'btn btn-primary', style: 'color: white;'