config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: 'visitors#index'
  devise_for :users
  resources :users do
    resources :routes do
      resources :alerts
    end
  end
end

app/models/alert.rb
class Alert < ApplicationRecord

  UNITS_TO_NAMES = {
    'hours' => 'hours before',
    'days' => 'days before',
    'weeks' => 'weeks before',
    'ASAP' => 'whenever a new event is added'
  }

  UNITS = UNITS_TO_NAMES.keys

  belongs_to :route
  validates :unit, presence: true, inclusion: { in: UNITS }
  validates :value, presence: true, unless: -> { unit == 'ASAP' }
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to [current_user, @alert.route], notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { redirect_to [current_user, Route.find(params[:route_id])] }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to [current_user, @alert.route], notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to user_route_url(current_user, @alert.route), notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:route_id, :value, :unit)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.slim
= form_for [current_user, alert.route, alert] do |f|
  - if alert.errors.any?
    #error_explanation
      h2 = "#{pluralize(alert.errors.count, "error")} prohibited this alert from being saved:"
      ul
        - alert.errors.full_messages.each do |message|
          li = message
  .field
    = f.number_field :value, step: 1, min: 0, max: 100, class: 'form-control', style: 'width: 60px;'
    | &nbsp;
    = f.select :unit, Alert::UNITS_TO_NAMES.to_a.map(&:reverse), class: 'form_control'
    | &nbsp;

    = f.hidden_field :route_id
    = f.submit '✔', class: 'btn btn-success btn-xs', style: 'float: right;'

javascript:

  var select = document.getElementById('alert_unit')
  var value = document.getElementById('alert_value')

  function updateVisibility() {
    value.style.display = select.value === 'ASAP' ? 'none' : 'inline'
  }

  select.addEventListener('change', updateVisibility)
  updateVisibility()

app/views/alerts/edit.html.slim
h1 Editing alert

== render 'form', alert: @alert

= link_to 'Back', user_route_path(current_user, @alert.route)

app/views/alerts/index.html.slim
h1 Listing alerts

table
  thead
    tr
      th Route
      th Value
      th Unit
      th
      th
      th

  tbody
    - @alerts.each do |alert|
      tr
        td = alert.route
        td = alert.value
        td = alert.unit
        td = link_to 'Show', alert
        td = link_to 'Edit', edit_alert_path(alert)
        td = link_to 'Destroy', alert, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Alert', new_alert_path